GET http://localhost:3002/matches/5/
###
GET http://localhost:3002/matches/1/players
### 
GET http://localhost:3002/players/1/playerScores
###
GET http://localhost:3002/players/4/matches
###
GET http://localhost:3002/players/